name: 'Release'

on:
  push:
    branches:
      - release

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

env:
  SEGMENT_DOWNLOAD_TIMEOUT_MIN: 3

jobs:
  release:
    name: 'Release'
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Checkout
        uses: actions/checkout@v3

      - name: Run install
        run: |
          yarn install

      - name: Semantic Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          yarn semantic-release
